# ?????
server:
  # ????
  port: 8080
  servlet:
    # ??????????
    context-path: /api

# ???????
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.169.32.129:3306/sks?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 1000
      initial-size: 100
      max-wait: 60000
      min-idle: 500
      # ???????????????????????????????
      time-between-eviction-runs-millis: 60000
      # ??????????????????????
      min-evictable-idle-time-millis: 300000
      # ????
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # ??PSCache??????????PSCache???
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      # ??connectProperties?????mergeSql????SQL??
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  # ??redis??
  redis:
    host: 192.168.32.129
    port: 6379
    timeout: 10
    lettuce:
      pool:
        max-active: 1000
        max-idle: 500
        max-wait: 500

  # ??RabbitMQ??
  rabbitmq:
    host: 192.168.32.129
    port: 5672
    username: mnsx
    password: 123123
    virtual-host: center
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0

# ??dao?XML?????????
mybatis:
  mapper-locations: classpath:mybatis/dao/*.xml

